// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HIT_MAPPING.Models
{
    [Table("buildings")]
    public partial class Building
    {
        public Building()
        {
            Rooms = new HashSet<Room>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("number")]
        public int Number { get; set; }

        [InverseProperty("Building")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}