// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HIT_MAPPING.Models
{
    [Table("roomTypes")]
    public partial class RoomType
    {
        public RoomType()
        {
            Rooms = new HashSet<Room>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("type")]
        [StringLength(50)]
        public string Type { get; set; } = null!;

        [InverseProperty("RoomType")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}